DELETE http://localhost:3003/api/blogs/67a155faa3bbf43cdb54794d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRpbW15IiwiaWQiOiI2N2ExNTRkODYxMzJiYzYyYTgzODMzYzkiLCJpYXQiOjE3Mzg2MjY0MzcsImV4cCI6MTczODYzMDAzN30.1u2_MjF6C1qzgC5y9adHBY3rgppwxbgbNMSzNlMyp-c