DELETE http://localhost:3003/api/blogs/67a0bd96bb353790a3c7af63
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRpbW15IiwiaWQiOiI2NzkzMTRkOWM2MmM1ODg1M2VlMzAyMmMiLCJpYXQiOjE3Mzg1ODczMjQsImV4cCI6MTczODU5MDkyNH0.iPfI9DZsTIXFV1l1You4pIlM8Nrumy4TK4_RdWo-IZA